<a href="https://colab.research.google.com/github/Ezra-Kaine/Probability/blob/main/data_transformation_and_data_association.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
file=files.upload()

Saving Bestsellers with categories (1).csv to Bestsellers with categories (1).csv

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv('Bestsellers with categories (1).csv')
df.head()

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         550 non-null    object
 1   Author       550 non-null    object
 2   User Rating  550 non-null    float64
 3   Reviews      550 non-null    int64
 4   Price        550 non-null    int64
 5   Year         550 non-null    int64
 6   Genre        550 non-null    object
dtypes: float64(1), int64(3), object(3)
memory usage: 30.2+ KB

In [5]:
df.isnull().sum()

Name           0
Author         0
User Rating    0
Reviews        0
Price          0
Year           0
Genre          0
dtype: int64

In [6]:
cat_cols = df.select_dtypes(include='object').columns

for col in cat_cols:
    print(f"\nColumn: {col}")
    print(df[col].value_counts())

Column: Name
Name
Publication Manual of the American Psychological Association, 6th Edition       10
StrengthsFinder 2.0                                                              9
Oh, the Places You'll Go!                                                        8
The Very Hungry Caterpillar                                                      7
The 7 Habits of Highly Effective People: Powerful Lessons in Personal Change     7
                                                                                ..
What to Expect When You're Expecting                                             1
What Should Danny Do? (The Power to Choose Series)                               1
What Pet Should I Get? (Classic Seuss)                                           1
What If?: Serious Scientific Answers to Absurd Hypothetical Questions            1
What Happened                                                                    1
Name: count, Length: 351, dtype: int64

Column: Author
Author
Jeff Kinney                           12
Suzanne Collins                       11
Gary Chapman                          11
Rick Riordan                          11
American Psychological Association    10
                                      ..
Maurice Sendak                         1
Cheryl Strayed                         1
The Staff of The Late Show with       1
Geneen Roth                            1
Ken Follett                            1
Name: count, Length: 248, dtype: int64

Column: Genre
Genre
Non Fiction    310
Fiction        240
Name: count, dtype: int64

In [9]:
bins = [0, 3, 7, 10]
labels = ['Poor', 'Good', 'Excellent']

df['Rating_category'] = pd.cut(df['User Rating'], bins=bins, labels=labels, include_lowest=True)

df[['User Rating', 'Rating_category']].head()

   User Rating Rating_category
0          4.7            Good
1          4.6            Good
2          4.7            Good
3          4.7            Good
4          4.8            Good

In [10]:
num_df = df.select_dtypes(include='number')

skewness = num_df.skew()

print("Skewness of numerical features:\n", skewness)

Skewness of numerical features:
 User Rating   -1.502125
Reviews        2.421597
Price          3.685057
Year           0.000000
dtype: float64

In [12]:
rating_genre = df.groupby('Genre')['User Rating'].mean()
print(rating_genre)

Genre
Fiction        4.648333
Non Fiction    4.595161
Name: User Rating, dtype: float64

In [14]:
correlation = df['User Rating'].corr(df['Price'])
print(f"Correlation between User Rating and Price: {correlation}")

Correlation between User Rating and Price: -0.13308628728087976